SNAP Rasdaman access and datacube viz
ua-snap/ardac-toolbox pull request #14
Opened 2023-11-17 22:10 UTC by kyleredilla

This PR adds a single notebook and some additional utility functions. 

The notebook breaks down using WCS to get a datacube from Rasdaman, and then provides a couple of examples of plotting with it. To test, make sure you can run the notebook and check typos and such! Also think about potential future enhancements for this notebook or more future notebooks, and comment on them or make some issues.

I again did not update the environment file, but the additional libraries needed are:

```
hvplot
panel
jupyter_bokeh
```

closes #7

2023-11-27 23:48 UTC, Joshdpaul requested changes
Kyle, this notebook is an excellent walk through of how to craft a WCS query. (I will probably refer back to this in the future!) The two new util functions are a great addition that allow the user to really quickly fetch/fuse the data and metadata. Very useful! 

I like both the plots; they are very "to the point" and don't require a ton of code, which I think keeps the focus on the data. Which I think works well for this notebook, which is more about accessing and understanding the coverages/datacube structure and less about cartography/plotting.

Most of my comments were fixing typos but there was one regarding the user inputs in the 3x1 plot. It looks like only the month input is used, and the model and scenario are just hard-coded. Not sure which direction you want to steer that?

One question is whether we will be able to host the notebooks in such a way as to have the final interactive plot useable through a web browser? That would be a great feature. I think being able to choose the dataset coordinates via point-and-click and then see the variable results is an effective way of explaining/transmitting the multidimensional nature of the coverage. To me, the list of coordinates/variables in the `xarray.Dataset` preview is less intuitive and I appreciate having the visualization / clickable component here. Nice work!

PS) I needed to also install `lxml` in my environment to use the new util functions

2023-11-27 23:48 UTC, Joshdpaul commented on notebooks/snap_rasdaman_access.ipynb
> +    "These data cubes are referred to as \"coverages\" in the protocols we will be using to access this data, so we will stick with that term for the remainder of this notebook. Read more about the c
```suggestion
    "These data cubes are referred to as \"coverages\" in the protocols we will be using to access this data, so we will stick with that term for the remainder of this notebook. Read more about the concept of a coverage at the [Open Geospatial Consortium's website](https://ogcapi.ogc.org/coverages/overview.html). \n",
```

2023-11-28 17:13 UTC, kyleredilla commented on notebooks/snap_rasdaman_access.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAA5EAAAFtCAYAAACeHe70AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjguMCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy81sbWrAAAACXBIWXMAAA9hAAAPYQGoP6dpAAEAAElEQVR4nOy
Fixed this, they were supposed to determine values for the first plot (which they do now)

2023-11-28 17:16 UTC, kyleredilla commented on notebooks/snap_rasdaman_access.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAA5EAAAFtCAYAAACeHe70AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjguMCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy81sbWrAAAACXBIWXMAAA9hAAAPYQGoP6dpAAEAAElEQVR4nOy
Yeah I am confused by the way this suggestion is formatted, so I fixed this in [51dc8d8](https://github.com/ua-snap/ardac-toolbox/pull/14/commits/51dc8d8041843609f82b2688057da5a57f72c9d5).

2023-11-28 17:26 UTC, kyleredilla commented
Thanks for the review @Joshdpaul ! I added all of your suggestions.

I agree that it would be ideal if the final hosting solution will allow the interactive plot to be usable through a web browser.

2023-11-28 17:26 UTC, merged