CMIP6 YK summary notebook
ua-snap/ardac-toolbox pull request #21
Opened 2024-07-23 17:07 UTC by kyleredilla

This PR is for a notebook that performs the work needed to summarize monthly CMIP6 temperature and precipitation data for a small project with IARC researchers. It was included in the `ardac-toolbox` repo because we anticipate this kind of request becoming more common, and having some code to point to would be helpful!

To test, simply execute the new notebook. Check for typos / poor writing since this could end up as a public-facing notebook. Feel free to explore the resulting data products in any additional ways!

The additional files needed for testing can be found in `/beegfs/CMIP6/kmredilla/ardac_toolbox_PR21_files`

2024-07-24 00:49 UTC, cstephen requested changes
I gave this notebook a careful read and it all makes sense to me. Excellent/thorough work & lots of it!! I've added a handful of PR code comments/suggestions/questions.

Also:
- [x] `xarray`, `rioxarray`, `cftime`, and `rasterio` are missing from `environment.yml` and should maybe be added as part of this PR.
- [ ] I was not able to run the notebook because `YK_domain_YDNWR_plus_ecoregion_akalb83.shp` is not included in this PR. Not sure if this was intention or not, but I didn't see any comments/instructions for how/where to download it either. I'll try running the notebook again once I track down this file.

2024-07-24 17:23 UTC, kyleredilla commented on notebooks/cmip6_polygon_summary.ipynb
> +    "Unfortunately, the time cooridantes are incorrect. If we decode manually:"
every time!

2024-07-24 17:39 UTC, kyleredilla commented on notebooks/cmip6_polygon_summary.ipynb
> +    "There are multiple polygons in this shapefile, and we really just need one for summarization over the coarse ~100km grid of the CMIP6 data, so we'll have to do some prep work. \n",
Good Q! fixed in [973255a](https://github.com/ua-snap/ardac-toolbox/pull/21/commits/973255a7c64afb15c194c052f0e28b809c2d3b0f)

2024-07-24 17:42 UTC, kyleredilla commented
Hey thanks @cstephen for the review! Sorry for all the typos. Also the shapefile is in `/beegfs/CMIP6/kmredilla/ardac_toolbox_PR21_files` on Chinook, sorry I didn't make that more clear in the PR comment - let me know if you can't get to it.

2024-07-24 18:03 UTC, cstephen commented on notebooks/cmip6_polygon_summary.ipynb
> +       "  grid-column: 1;\n",
Looks like the PR code suggestion formatting fell apart here, but this was just a minor grammar nitpick. I suggested changing:

> Now just write to a file for both of temperature and precipitation

To:

> Now just write to a file for both temperature and precipitation

2024-07-24 18:13 UTC, kyleredilla commented on notebooks/cmip6_polygon_summary.ipynb
> +       "  grid-column: 1;\n",
Ah okay! Fixed.

2024-07-26 18:09 UTC, cstephen commented
Since this PR works great and it's only the conda `environment.yml` that has been giving me problems, I've reverted to the version of `environment.yml` from the `main` branch and captured the work left to do (+ some new tips) in issue #22.

2024-07-26 18:09 UTC, merged